### ISSUE TITLE
Go1.19

### ISSUE THREAD

**Issue by AYSHSTUDIO** [imshuai/serverchan#1]
你好！最新的Go1.19中出现以下错误，请问我应该如何处理
panic: interface conversion: interface {} is nil, not float64

**Comment by rayepeng** [comment]
我也遇到了这个问题，返回的resp body如下：

```json
"{\"code\":0,\"message\":\"\",\"data\":{\"pushid\":\"116930522\",\"readkey\":\".....\",\"error\":\"SUCCESS\",\"errno\":0}}"
```

**Comment by rayepeng** [comment]
提了个pr fix

或者也可以引用我的 `import "github.com/rayepeng/serverchan"`
https://github.com/imshuai/serverchan/pull/2

**Comment by imshuai** [comment]
## merged  
---  
没想到自己随便写的一个小工具也有人仔细找bug提PR，瑞斯拜

**Comment by rayepeng** [comment]
> ## merged  
> 
> ---  
> 
> 没想到自己随便写的一个小工具也有人仔细找bug提PR，瑞斯拜

哈哈哈哈
